Enforce cython ==0.21 version
As recommended by @stuarteberg to make it work on Linux
(CentOS 5.11, same as Anaconda's build server)

Without this, it fails thus:
# Cythonize both DASSL and DASPK3.1 wrappers
python setup.py build_ext daspk --inplace
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
make: *** [cython] Error 1
Command failed: /bin/bash -x -e /home/ilastik/conda-recipes/pydas/build.sh

With, it works. He uploaded the resulting binary to binstar 
(channel stuarteberg)

Thanks!