llvm_null: Test-case for conda-build 3 'exact=True' bug?
Ping @msarahan. I will dig into this myself now, but in-case you have time
I'd appreciate your thoughts.

Here we have a simple dependency chain with no cycles:
clang => llvm => llvm-lto-tapi => libcxx-osx_64 => libcxxabi-osx_64

Attempting to build it causes:

```
Attempting to finalize metadata for clang
INFO:conda_build.metadata:Attempting to finalize metadata for clang
Attempting to finalize metadata for libcxxabi_osx-64
INFO:conda_build.metadata:Attempting to finalize metadata for libcxxabi_osx-64
Attempting to finalize metadata for llvm
INFO:conda_build.metadata:Attempting to finalize metadata for llvm
Attempting to finalize metadata for llvm-lto-tapi
INFO:conda_build.metadata:Attempting to finalize metadata for llvm-lto-tapi
Attempting to finalize metadata for libcxx_osx-64
INFO:conda_build.metadata:Attempting to finalize metadata for libcxx_osx-64
Traceback (most recent call last):
  File "/Users/rdonnelly/mc-x64-3.6/bin/conda-build", line 11, in <module>
    load_entry_point('conda-build==3.0.10+1.g9738cd40', 'console_scripts', 'conda-build')()
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 387, in main
    execute(sys.argv[1:])
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 378, in execute
    noverify=args.no_verify)
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/build.py", line 1743, in build_tree
    notest=notest,
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/build.py", line 885, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/render.py", line 501, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/metadata.py", line 1733, in get_output_metadata_set
    ensure_matching_hashes(conda_packages)
  File "/Users/rdonnelly/mc-x64-3.6/lib/python3.6/site-packages/conda_build/metadata.py", line 279, in ensure_matching_hashes
    "Involved packages were:\n" + error)
conda_build.exceptions.RecipeError: Mismatching hashes in recipe. Exact pins in dependencies that contribute to the hash often cause this. Can you change one or more exact pins to version bound constraints?
Involved packages were:
Mismatching package: llvm; consumer package: clang
```

Interestingly, removing the libcxxabi-osx_64 package avoids this issue.